runtime: java11
service: description-service  # Replace with your desired service name

env_variables:
  SPRING_DATASOURCE_URL: jdbc:mysql://description-mysql:3306/descriptiondb?allowPublicKeyRetrieval=true&autoReconnect=true&useSSL=false
  SPRING_DATASOURCE_USERNAME: root
  SPRING_DATASOURCE_PASSWORD: m@nipassword

automatic_scaling:
  target_cpu_utilization: 0.65
